### ISSUE TITLE
division by zero

### ISSUE THREAD

**Issue by Li-An** [dipakcg/dcg-display-plugin-data#1]
For some reason, I’ve got this error message
_Warning: Division by zero in www/blog/wp-content/plugins/dcg-display-plugin-data/dcg-display-plugin-data.php on line 41_  
with this plugin: https://wordpress.org/plugins/phoenix-media-rename/

**Comment by dipakcg** [comment]
Duplicate thread : https://wordpress.org/support/topic/division-by-zero-7
